[package]
name = "iroh"
version = "0.15.0"
edition = "2021"
readme = "README.md"
description = "Bytes. Distributed."
license = "MIT OR Apache-2.0"
authors = ["dignifiedquire <me@dignifiedquire.com>", "n0 team"]
repository = "https://github.com/n0-computer/iroh"
keywords = ["networking", "p2p", "holepunching", "ipfs"]

# Sadly this also needs to be updated in .github/workflows/ci.yml
rust-version = "1.75"

[lints]
workspace = true

[dependencies]
anyhow = { version = "1" }
bao-tree = { version = "0.13", features = ["tokio_fsm"], default-features = false }
bytes = "1"
derive_more = { version = "1.0.0-beta.6", features = ["debug", "display", "from", "try_into", "from_str"] }
flume = "0.11"
futures-buffered = "0.2.4"
futures-lite = "2.3"
futures-util = "0.3"
genawaiter = { version = "0.99", default-features = false, features = ["futures03"] }
hex = { version = "0.4.3" }
iroh-bytes = { version = "0.15.0", path = "../iroh-bytes", features = ["downloader"] }
iroh-base = { version = "0.15.0", path = "../iroh-base", features = ["key"] }
iroh-io = { version = "0.6.0", features = ["stats"] }
iroh-metrics = { version = "0.15.0", path = "../iroh-metrics", optional = true }
iroh-net = { version = "0.15.0", path = "../iroh-net" }
num_cpus = { version = "1.15.0" }
portable-atomic = "1"
iroh-sync = { version = "0.15.0", path = "../iroh-sync" }
iroh-gossip = { version = "0.15.0", path = "../iroh-gossip" }
parking_lot = "0.12.1"
postcard = { version = "1", default-features = false, features = ["alloc", "use-std", "experimental-derive"] }
quic-rpc = { version = "0.8.0", default-features = false, features = ["flume-transport", "quinn-transport"] }
quinn = "0.10"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
strum = { version = "0.25", features = ["derive"] }
thiserror = "1"
tempfile = "3.4"
tokio = { version = "1", features = ["io-util", "rt"] }
tokio-stream = "0.1"
tokio-util = { version = "0.7", features = ["codec", "io-util", "io", "time"] }
tracing = "0.1"
walkdir = "2"

# Examples
clap = { version = "4", features = ["derive"], optional = true }
indicatif = { version = "0.17", features = ["tokio"], optional = true }

[features]
default = ["metrics", "fs-store"]
metrics = ["iroh-metrics", "iroh-bytes/metrics"]
fs-store = ["iroh-bytes/fs-store"]
test = []
examples = ["dep:clap", "dep:indicatif"]
test-utils = ["iroh-net/test-utils"]

[dev-dependencies]
anyhow = { version = "1" }
bytes = "1"
genawaiter = { version = "0.99", features = ["futures03"] }
iroh = { path = ".", features = ["test-utils"] }
iroh-test = { path = "../iroh-test" }
proptest = "1.2.0"
rand_chacha = "0.3.1"
regex = { version = "1.7.1", features = ["std"] }
serde_json = "1.0.107"
testdir = "0.9.1"
tokio = { version = "1", features = ["macros", "io-util", "rt"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[package.metadata.docs.rs]
all-features = true
# enable unstable features in the documentation
rustdoc-args = ["--cfg", "docsrs"]


[[example]]
name = "hello-world-provide"

[[example]]
name = "hello-world-fetch"

[[example]]
name = "collection-provide"

[[example]]
name = "collection-fetch"

[[example]]
name = "rpc"
required-features = ["examples"]

[[example]]
name = "client"
required-features = ["examples"]
